apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: nginx-ingress
    repoURL: https://helm.nginx.com/stable
    helm:
      releaseName: health-service-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
