apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status-page
  namespace: argocd
spec:
  project: default
  source:
    chart: wordpress
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.3.2
  destination:
    server: https://kubernetes.default.svc
    namespace: status-page
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
