apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: argocd
spec:
  project: default
  source:
    chart: hashicorp-vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 1.10.3
    helm:
      releaseName: hashicorp-vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
