apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        editor: vscode
        app: web
    spec:
      containers:
      - name: demo-app
        image: nginx
        ports:
          - containerPort: 80
