apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandbox-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mhorlbeck-sans/argo-manifests.git
    targetRevision: HEAD
    path: management-cluster/environments/sandbox
  destination:
    server: https://kubernetes.default.svc
    namespace: app-of-apps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
